### PR TITLE
asm block and some other stuff

### PR DESCRIPTION
**Pull request by xf8b**
the very concern

- [x] do the thing
- [x] model blockstate and texture
- [x] translation 
- [x] check if it runs in a regular minecraft instance
- [x] check if it runs with java 8

### CODE REVIEW

**Review by zAG6z — CHANGES_REQUESTED** [review]
remove asm block pls thx

**Comment by BHLoneWolf0** [comment]
asm cringe

**Comment by xf8b** [comment]
no u

**Comment by xf8b** [comment]
not cool

**Review by zAG6z — CHANGES_REQUESTED** [review]
remove asm block pls thx and dont dismiss my review pls thx

**Comment by xf8b** [comment]
no

**Comment by zAG6z** [comment]
why

**Comment by xf8b** [comment]
it is the funny easter egg

**Review by zAG6z — CHANGES_REQUESTED** [review]
a s m block be gone thx

**Comment by zAG6z** [comment]
ok

**Comment by zAG6z** [comment]
> it is the funny easter egg

ok

**Review by zAG6z — APPROVED** [review]
smh

**Pull request merged**
