### PR TITLE
update :yarn: to 1.16.5 build 3

### PR DESCRIPTION
**Pull request by xf8b**

### CODE REVIEW

**Review by zAG6z — CHANGES_REQUESTED** [review]
ok

**Review by zAG6z — APPROVED** [review]
ok

**Review by zAG6z — CHANGES_REQUESTED** [review]
no

**Review by zAG6z — APPROVED** [review]
ok

**Comment by xf8b** [comment]
@zAG6z plas dssdgry aetdhateheath

**Review by zAG6z — CHANGES_REQUESTED** [review]
erdfth  tgujf tfgh f

**Review by zAG6z — APPROVED** [review]
o8wmj593 sdf cf ?DF.g./ dfijo dre r ds 4ie 458

**Comment by xf8b** [comment]
thx

**Pull request merged**
